### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by janci14** [knjk04/coffee-roulette#1]
Hello, 
I was trying to run your app, but I got stuck at what I understand comunication with backend. I was trying to solve CORS, but it seem to me that everything is set correctly. 

Thank you.
![image](https://user-images.githubusercontent.com/124784684/217518331-782129af-de1f-418c-8c74-bbb9fee6a932.png)

**Comment by knjk04** [comment]
Hi @janci14, thanks for letting me know you are facing this problem. Unfortunately, I am no longer working on this project.
